// AUTO-GENERATED: every photo from the supplied content/ folder, for the gallery.
import type { GalleryItem } from "@/components/sections/MasonryGallery";

export const CONTENT_GALLERY: GalleryItem[] = [
  { src: "/media/content/chigwell-hall-4e.jpg", alt: "Chigwell Hall and its suites on the estate", width: 1600, height: 1066, cat: "weddings" },
  { src: "/media/content/chigwell-hall-4b.jpg", alt: "Chigwell Hall and its suites on the estate", width: 5464, height: 3643, cat: "weddings" },
  { src: "/media/content/chigwell-hall-4a.jpg", alt: "Chigwell Hall and its suites on the estate", width: 4368, height: 2912, cat: "weddings" },
  { src: "/media/content/mini-03fde31a-9817-4ac3-b40d-b09c6a34a94c.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 1512, height: 1512, cat: "weddings" },
  { src: "/media/content/mini-6-mini-marquee-3.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 4000, height: 3000, cat: "weddings" },
  { src: "/media/content/mini-photo-188.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 6636, height: 4424, cat: "weddings" },
  { src: "/media/content/mini-photo-202.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 8200, height: 5467, cat: "weddings" },
  { src: "/media/content/mini-f0b138d4-6b91-488f-ab74-f8e1e360b768.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 1000, height: 667, cat: "weddings" },
  { src: "/media/content/mini-20190517-152537.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 3024, height: 3024, cat: "weddings" },
  { src: "/media/content/mini-6-mini-marquee-5.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 4000, height: 3000, cat: "weddings" },
  { src: "/media/content/mini-mi-3.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 6000, height: 4000, cat: "weddings" },
  { src: "/media/content/mini-photo-3.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 6600, height: 4400, cat: "weddings" },
  { src: "/media/content/mini-20230519-184055.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 4000, height: 3000, cat: "weddings" },
  { src: "/media/content/mini-8d.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 1600, height: 777, cat: "weddings" },
  { src: "/media/content/mini-photo-153.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 7008, height: 4672, cat: "weddings" },
  { src: "/media/content/mini-8e.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 4000, height: 3000, cat: "weddings" },
  { src: "/media/content/mini-2.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 4032, height: 3024, cat: "weddings" },
  { src: "/media/content/mini-8a.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 1500, height: 2000, cat: "weddings" },
  { src: "/media/content/mini-8c.jpg", alt: "Inside the Mini Marquee, dressed for a celebration", width: 5438, height: 3625, cat: "weddings" },
  { src: "/media/content/pictures-photo-573.jpg", alt: "An Asian wedding at The Chigwell Marquees", width: 6604, height: 4403, cat: "asian" },
  { src: "/media/content/pictures-10a.jpg", alt: "A celebration at The Chigwell Marquees", width: 1600, height: 1056, cat: "weddings" },
  { src: "/media/content/pictures-photo-262.jpg", alt: "A celebration at The Chigwell Marquees", width: 4595, height: 6893, cat: "weddings" },
  { src: "/media/content/pictures-10b.jpg", alt: "A celebration at The Chigwell Marquees", width: 3840, height: 5760, cat: "weddings" },
  { src: "/media/content/pictures-10c.jpg", alt: "An Asian wedding at The Chigwell Marquees", width: 1000, height: 667, cat: "asian" },
  { src: "/media/content/pictures-photo-120.jpg", alt: "A celebration at The Chigwell Marquees", width: 4623, height: 6936, cat: "weddings" },
  { src: "/media/content/pictures-4d.jpg", alt: "A celebration at The Chigwell Marquees", width: 1067, height: 1600, cat: "weddings" },
  { src: "/media/content/pictures-photo-178.jpg", alt: "A celebration at The Chigwell Marquees", width: 8166, height: 5444, cat: "weddings" },
  { src: "/media/content/pictures-photo-557.jpg", alt: "A celebration at The Chigwell Marquees", width: 5613, height: 3742, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-13b.jpg", alt: "Chigwell Hall and its suites on the estate", width: 1999, height: 1264, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-13c.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1251, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-13a.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1255, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-12d.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1500, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-12a.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1500, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-12c.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1500, cat: "weddings" },
  { src: "/media/content/chigwell-hall-rooms-12b.jpg", alt: "Chigwell Hall and its suites on the estate", width: 2000, height: 1500, cat: "weddings" },
  { src: "/media/content/mega-venue5-450-guest.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 1600, height: 1066, cat: "weddings" },
  { src: "/media/content/mega-photo-28.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 6000, height: 4000, cat: "weddings" },
  { src: "/media/content/mega-a2-portrait.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 4000, height: 3000, cat: "weddings" },
  { src: "/media/content/mega-9.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 5616, height: 3738, cat: "weddings" },
  { src: "/media/content/mega-3j7a1689.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 5760, height: 3840, cat: "weddings" },
  { src: "/media/content/mega-gimage.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 2048, height: 1366, cat: "weddings" },
  { src: "/media/content/mega-4bdnnvby.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 5472, height: 3648, cat: "weddings" },
  { src: "/media/content/mega-photo-122.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 7008, height: 4672, cat: "weddings" },
  { src: "/media/content/mega-image-5.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 4418, height: 2482, cat: "weddings" },
  { src: "/media/content/mega-whatsapp-image-2025-02-02-at-20-08-14.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 1600, height: 1067, cat: "weddings" },
  { src: "/media/content/mega-photo-543.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 5745, height: 3830, cat: "weddings" },
  { src: "/media/content/mega-mega-marquee5.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 5838, height: 3892, cat: "weddings" },
  { src: "/media/content/mega-photo-35.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 7008, height: 4672, cat: "weddings" },
  { src: "/media/content/mega-mendhi-stage.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 1600, height: 777, cat: "weddings" },
  { src: "/media/content/mega-img-1110.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 2732, height: 1417, cat: "weddings" },
  { src: "/media/content/mega-mega-marquee2.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 1600, height: 1066, cat: "weddings" },
  { src: "/media/content/mega-mega-marquee3.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 6000, height: 4000, cat: "weddings" },
  { src: "/media/content/mega-photo-183.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 6339, height: 4226, cat: "weddings" },
  { src: "/media/content/mega-dsc-0834.jpg", alt: "Inside the Mega Marquee, dressed for a celebration", width: 6016, height: 4016, cat: "weddings" },
  { src: "/media/content/extras-10f.jpg", alt: "The grounds and gardens of the Chigwell Hall estate", width: 4032, height: 3024, cat: "weddings" },
  { src: "/media/content/extras-main.jpg", alt: "The grounds and gardens of the Chigwell Hall estate", width: 3208, height: 1836, cat: "weddings" },
  { src: "/media/content/extras-mega-marquee-or-grounds.jpg", alt: "The grounds and gardens of the Chigwell Hall estate", width: 1600, height: 1143, cat: "weddings" },
];
