// AUTO-GENERATED from the "New Images" folder — real wedding photography,
// resized to 2048px / q80 for the web. Shown on the /gallery page only.
import type { GalleryItem } from "@/components/sections/MasonryGallery";

export const NEW_GALLERY: GalleryItem[] = [
  { src: "/media/new/new-0001.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0002.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0003.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0004.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0005.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0006.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0007.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0008.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0009.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0010.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0011.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1337, cat: "weddings" },
  { src: "/media/new/new-0012.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1389, cat: "weddings" },
  { src: "/media/new/new-0013.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0014.jpg", alt: "A wedding at The Chigwell Marquees", width: 1374, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0015.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0016.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0017.jpg", alt: "A wedding at The Chigwell Marquees", width: 1425, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0018.jpg", alt: "A wedding at The Chigwell Marquees", width: 1363, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0019.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1335, cat: "weddings" },
  { src: "/media/new/new-0020.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0021.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1359, cat: "weddings" },
  { src: "/media/new/new-0022.jpg", alt: "A wedding at The Chigwell Marquees", width: 1392, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0023.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1152, cat: "asian" },
  { src: "/media/new/new-0024.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1152, cat: "asian" },
  { src: "/media/new/new-0025.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0026.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0027.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0028.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0029.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0030.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0031.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0032.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0033.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0034.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0035.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0036.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0037.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0038.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0039.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0040.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0041.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0042.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0043.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0044.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0045.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0046.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0047.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0048.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0049.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0050.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0051.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0052.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0053.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0054.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0055.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0056.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0057.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0058.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0059.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0060.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0061.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0062.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0063.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0064.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0065.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0066.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0067.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0068.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0069.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0070.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0071.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0072.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0073.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0074.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0075.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0076.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0077.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0078.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0079.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0080.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0081.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0082.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0083.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0084.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0085.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0086.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0087.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0088.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1362, cat: "weddings" },
  { src: "/media/new/new-0089.jpg", alt: "A wedding at The Chigwell Marquees", width: 1362, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0090.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1362, cat: "weddings" },
  { src: "/media/new/new-0091.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0092.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0093.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0094.jpg", alt: "A wedding at The Chigwell Marquees", width: 1364, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0095.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0096.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0097.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0098.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0099.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0100.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0101.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0102.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0103.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0104.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0105.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0106.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0107.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1150, cat: "weddings" },
  { src: "/media/new/new-0108.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1150, cat: "weddings" },
  { src: "/media/new/new-0109.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1150, cat: "weddings" },
  { src: "/media/new/new-0110.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1172, cat: "weddings" },
  { src: "/media/new/new-0111.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0112.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0113.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0114.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0115.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0116.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0117.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0118.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0119.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0120.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0121.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 2048, height: 1365, cat: "asian" },
  { src: "/media/new/new-0122.jpg", alt: "An Asian wedding celebration at The Chigwell Marquees", width: 1365, height: 2048, cat: "asian" },
  { src: "/media/new/new-0123.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0124.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0125.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0126.jpg", alt: "A wedding at The Chigwell Marquees", width: 1365, height: 2048, cat: "weddings" },
  { src: "/media/new/new-0127.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0128.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0129.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0130.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
  { src: "/media/new/new-0131.jpg", alt: "A wedding at The Chigwell Marquees", width: 2048, height: 1365, cat: "weddings" },
];
